import {createClient} from '@/lib/supabase/server'
import {PageHead,Stat,Empty,Badge} from '@/components/ui'
import {createRoom,setRoomActive,addRoomAvailability,removeRoomAvailability} from './actions'
const days=['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
export default async function Page({searchParams}:{searchParams:Promise<{success?:string,error?:string,details?:string}>}){
 const s=await createClient(),p=await searchParams
 const [rr,tr,sr,ar]=await Promise.all([
  s.from('rooms').select('id,code,name,building,floor,capacity,is_active,room_type_id,room_types(name)').order('code'),
  s.from('room_types').select('id,name').order('name'),
  s.from('semesters').select('id,name,is_active,academic_years(name)').order('start_date',{ascending:false}),
  s.from('room_availability').select('id,room_id,semester_id,day_of_week,start_time,end_time,status,reason').order('day_of_week').order('start_time')])
 const rooms=rr.data??[],types=tr.data??[],semesters=sr.data??[],availability=ar.data??[],active=semesters.find((x:any)=>x.is_active)
 const msg:any={room_created:'Room created successfully.',room_updated:'Room status updated.',availability_created:'Room availability saved.',availability_removed:'Room availability removed.'}
 const err:any={invalid_room:'Enter a room code, name, and valid capacity.',institution_missing:'Create/configure the institution record first.',room_create_failed:'Room could not be created.',room_missing:'Room not found.',room_update_failed:'Room could not be updated.',invalid_availability:'Complete the availability form with a valid day/time/status.',availability_create_failed:'Availability could not be saved.',availability_missing:'Availability record not found.',availability_delete_failed:'Availability could not be removed.'}
 return <><PageHead eyebrow="RESOURCES" title="Rooms" description="Manage rooms, capacities, types, and semester availability used by the scheduling engine."/>
 <div className="stats-grid"><Stat label="Rooms" value={rooms.length}/><Stat label="Active Rooms" value={rooms.filter((x:any)=>x.is_active).length}/><Stat label="Room Types" value={types.length}/><Stat label="Availability Records" value={availability.length}/></div>
 {p.success&&<div className="sched-alert sched-alert-success"><div><strong>Success</strong><span>{msg[p.success]??'Saved.'}</span></div></div>}
 {p.error&&<div className="sched-alert sched-alert-danger"><div><strong>Action failed</strong><span>{err[p.error]??'Operation failed.'}{p.details?` Database: ${p.details}`:''}</span></div></div>}
 <section className="sched-section"><div className="sched-section-head"><div className="sched-section-copy"><span className="sched-kicker">ROOM SETUP</span><h3>Add Room</h3><p>Create schedulable rooms and define their capacities and types.</p></div></div><div className="sched-section-body">
 <form action={createRoom} className="sched-form"><div className="sched-form-grid">
 <div className="sched-field"><label>Room Code</label><input name="code" placeholder="Room code" required/></div><div className="sched-field"><label>Name</label><input name="name" placeholder="Room name" required/></div>
 <div className="sched-field"><label>Room Type</label><select name="room_type_id"><option value="">General / Unspecified</option>{types.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
 <div className="sched-field"><label>Capacity</label><input name="capacity" type="number" min="1" required/></div><div className="sched-field"><label>Building</label><input name="building"/></div><div className="sched-field"><label>Floor</label><input name="floor"/></div></div><div className="sched-form-actions"><button className="sched-primary-btn">Create Room</button></div></form></div></section>
 <section className="sched-section"><div className="sched-section-head"><div className="sched-section-copy"><span className="sched-kicker">ROOM DIRECTORY</span><h3>Configured Rooms</h3></div><Badge>{rooms.length} Total</Badge></div><div className="sched-section-body">{rooms.length?<div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Code</th><th>Name</th><th>Building</th><th>Capacity</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{rooms.map((x:any)=>{const rt=Array.isArray(x.room_types)?x.room_types[0]:x.room_types;return <tr key={x.id}><td><strong>{x.code}</strong></td><td>{x.name}</td><td>{x.building||'—'}</td><td>{x.capacity}</td><td>{rt?.name||'—'}</td><td><Badge tone={x.is_active?'success':'warning'}>{x.is_active?'Active':'Inactive'}</Badge></td><td><form action={setRoomActive}><input type="hidden" name="room_id" value={x.id}/><input type="hidden" name="active" value={String(!x.is_active)}/><button className="sched-secondary-btn">{x.is_active?'Deactivate':'Activate'}</button></form></td></tr>})}</tbody></table></div>:<Empty text="No rooms configured."/>}</div></section>
 <section className="sched-section"><div className="sched-section-head"><div className="sched-section-copy"><span className="sched-kicker">AVAILABILITY</span><h3>Room Availability</h3><p>Mark semester time windows as available, blocked, or under maintenance.</p></div></div><div className="sched-section-body">
 <form action={addRoomAvailability} className="sched-form"><div className="sched-form-grid"><div className="sched-field"><label>Room</label><select name="room_id" required><option value="">Select Room</option>{rooms.filter((x:any)=>x.is_active).map((x:any)=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div><div className="sched-field"><label>Semester</label><select name="semester_id" defaultValue={active?.id??''} required><option value="">Select Semester</option>{semesters.map((x:any)=><option key={x.id} value={x.id}>{x.name}{x.is_active?' (Active)':''}</option>)}</select></div><div className="sched-field"><label>Day</label><select name="day_of_week" required><option value="">Select Day</option>{days.slice(1).map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select></div><div className="sched-field"><label>Start</label><input type="time" name="start_time" required/></div><div className="sched-field"><label>End</label><input type="time" name="end_time" required/></div><div className="sched-field"><label>Status</label><select name="status" defaultValue="available"><option value="available">Available</option><option value="blocked">Blocked</option><option value="maintenance">Maintenance</option></select></div><div className="sched-field"><label>Reason</label><input name="reason" placeholder="Optional"/></div></div><div className="sched-form-actions"><button className="sched-primary-btn">Add Availability</button></div></form>
 {availability.length>0&&<div style={{overflowX:'auto',marginTop:20}}><table className="data-table"><thead><tr><th>Room</th><th>Day</th><th>Time</th><th>Status</th><th>Reason</th><th></th></tr></thead><tbody>{availability.map((a:any)=>{const r=rooms.find((x:any)=>x.id===a.room_id);return <tr key={a.id}><td>{r?.code||'—'}</td><td>{days[a.day_of_week]}</td><td>{a.start_time.slice(0,5)} – {a.end_time.slice(0,5)}</td><td><Badge>{a.status}</Badge></td><td>{a.reason||'—'}</td><td><form action={removeRoomAvailability}><input type="hidden" name="availability_id" value={a.id}/><button className="sched-secondary-btn">Remove</button></form></td></tr>})}</tbody></table></div>}
 </div></section></>}
