import {requireRole} from '@/lib/auth/require-role';
import {createClient} from '@/lib/supabase/server';
import {PageHead,Empty,Badge} from '@/components/ui';
import {submitChangeRequest} from './actions'
const days=['','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
export default async function Page({searchParams}:{searchParams?:Promise<Record<string,string|undefined>>}){const p=searchParams?await searchParams:{};
const {profile}=await requireRole(['faculty']);
const s=await createClient();
const {data:f}=await s.from('faculty_profiles').select('id').eq('profile_id',profile.id).maybeSingle();
const {data:entries}=f?await s.from('schedule_entries').select('id,day_of_week,start_time,end_time,rooms(id,code),class_offerings(subjects(code,name)),schedule_versions!inner(status)').eq('faculty_id',f.id).eq('schedule_versions.status','published').order('day_of_week').order('start_time'):{data:[] as any[]};
const {data:rooms}=await s.from('rooms').select('id,code,name').eq('is_active',true).order('code');
const {data}=await s.from('schedule_change_requests').select('id,reason,status,change_type,created_at').eq('requested_by',profile.id).order('created_at',{ascending:false});
return <><PageHead eyebrow="ALTERATIONS" title="My Alteration Requests" description="Request a change to one of your published classes and track its review status."/>{p.success&&<div className="portal-alert portal-alert-success"><strong>Request submitted.</strong><span>It is now awaiting administrative review.</span></div>}{p.error&&<div className="portal-alert portal-alert-danger"><strong>Request failed.</strong><span>{p.error}</span></div>}<div className="panel"><h3>New Request</h3><form action={submitChangeRequest} className="sched-form"><div className="sched-form-grid"><div className="sched-field"><label>Published Class</label><select name="schedule_entry_id" required><option value="">Select class</option>{(entries??[]).map((x:any)=><option key={x.id} value={x.id}>{days[x.day_of_week]} {x.start_time.slice(0,5)}–{x.end_time.slice(0,5)} · {x.class_offerings?.[0]?.subjects?.[0]?.code??'Class'}</option>)}</select></div><div className="sched-field"><label>Change Type</label><select name="change_type" defaultValue="normal_request"><option value="normal_request">Normal request</option><option value="emergency">Emergency</option></select></div><div className="sched-field"><label>Proposed Day</label><select name="proposed_day"><option value="">Keep current</option>{days.slice(1).map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select></div><div className="sched-field"><label>Proposed Start</label><input type="time" name="proposed_start_time"/></div><div className="sched-field"><label>Proposed End</label><input type="time" name="proposed_end_time"/></div><div className="sched-field"><label>Proposed Room</label><select name="proposed_room_id"><option value="">Keep current</option>{(rooms??[]).map((r:any)=><option key={r.id} value={r.id}>{r.code} — {r.name}</option>)}</select></div><div className="sched-field" style={{gridColumn:'1 / -1'}}><label>Reason</label><textarea name="reason" required rows={3}/></div></div><div className="sched-form-actions"><button className="sched-primary-btn">Submit Request</button></div></form></div><div className="panel"><h3>Request History</h3>{data?.length?<table className="data-table"><thead><tr><th>Reason</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.reason}</td><td>{x.change_type.replaceAll('_',' ')}</td><td><Badge>{x.status}</Badge></td><td>{new Date(x.created_at).toLocaleDateString('en-PH')}</td></tr>)}</tbody></table>:<Empty text="No alteration requests submitted."/>}</div></>}
